Remove --cache-to option
Got an error like:

ERROR: Cache export feature is currently not supported for docker driver.
Please switch to a different driver (eg. "docker buildx create --use")